# Create a Web Application for an ETF Analyzer

In this Challenge assignment, you’ll build a financial database and web application by using SQL, Python, and the Voilà library to analyze the performance of a hypothetical fintech ETF.

Instructions: 

Use this notebook to complete your analysis of a fintech ETF that consists of four stocks: GOST, GS, PYPL, and SQ. Each stock has its own table in the `etf.db` database, which the `Starter_Code` folder also contains.

Analyze the daily returns of the ETF stocks both individually and as a whole. Then deploy the visualizations to a web application by using the Voilà library.

The detailed instructions are divided into the following parts:

* Analyze a single asset in the ETF

* Optimize data access with Advanced SQL queries

* Analyze the ETF portfolio

* Deploy the notebook as a web application

#### Analyze a Single Asset in the ETF

For this part of the assignment, you’ll use SQL queries with Python, Pandas, and hvPlot to analyze the performance of a single asset from the ETF.

Complete the following steps:

1. Write a SQL `SELECT` statement by using an f-string that reads all the PYPL data from the database. Using the SQL `SELECT` statement, execute a query that reads the PYPL data from the database into a Pandas DataFrame.

2. Use the `head` and `tail` functions to review the first five and the last five rows of the DataFrame. Make a note of the beginning and end dates that are available from this dataset. You’ll use this information to complete your analysis.

3. Using hvPlot, create an interactive visualization for the PYPL daily returns. Reflect the “time” column of the DataFrame on the x-axis. Make sure that you professionally style and format your visualization to enhance its readability.

4. Using hvPlot, create an interactive visualization for the PYPL cumulative returns. Reflect the “time” column of the DataFrame on the x-axis. Make sure that you professionally style and format your visualization to enhance its readability.

#### Optimize Data Access with Advanced SQL Queries

For this part of the assignment, you’ll continue to analyze a single asset (PYPL) from the ETF. You’ll use advanced SQL queries to optimize the efficiency of accessing data from the database.

Complete the following steps:

1. Access the closing prices for PYPL that are greater than 200 by completing the following steps:

    - Write a SQL `SELECT` statement to select the dates where the PYPL closing price was higher than 200.0.

    - Using the SQL statement, read the data from the database into a Pandas DataFrame, and then review the resulting DataFrame.

    - Select the “time” and “close” columns for those dates where the closing price was higher than 200.0.

2. Find the top 10 daily returns for PYPL by completing the following steps:

    -  Write a SQL statement to find the top 10 PYPL daily returns. Make sure to do the following:

        * Use `SELECT` to select only the “time” and “daily_returns” columns.

        * Use `ORDER` to sort the results in descending order by the “daily_returns” column.

        * Use `LIMIT` to limit the results to the top 10 daily return values.

    - Using the SQL statement, read the data from the database into a Pandas DataFrame, and then review the resulting DataFrame.

#### Analyze the ETF Portfolio

For this part of the assignment, you’ll build the entire ETF portfolio and then evaluate its performance. To do so, you’ll build the ETF portfolio by using SQL joins to combine all the data for each asset.

Complete the following steps:

1. Write a SQL query to join each table in the portfolio into a single DataFrame. To do so, complete the following steps:

    - Use a SQL inner join to join each table on the “time” column. Access the “time” column in the `GDOT` table via the `GDOT.time` syntax. Access the “time” columns from the other tables via similar syntax.

    - Using the SQL query, read the data from the database into a Pandas DataFrame. Review the resulting DataFrame.

2. Create a DataFrame that averages the “daily_returns” columns for all four assets. Review the resulting DataFrame.

    > **Hint** Assuming that this ETF contains equally weighted returns, you can average the returns for each asset to get the average returns of the portfolio. You can then use the average returns of the portfolio to calculate the annualized returns and the cumulative returns. For the calculation to get the average daily returns for the portfolio, use the following code:
    >
    > ```python
    > etf_portfolio_returns = etf_portfolio['daily_returns'].mean(axis=1)
    > ```
    >
    > You can use the average daily returns of the portfolio the same way that you used the daily returns of a single asset.

3. Use the average daily returns in the `etf_portfolio_returns` DataFrame to calculate the annualized returns for the portfolio. Display the annualized return value of the ETF portfolio.

> **Hint**  To calculate the annualized returns, multiply the mean of the `etf_portfolio_returns` values by 252.
>
> To convert the decimal values to percentages, multiply the results by 100.

4. Use the average daily returns in the `etf_portfolio_returns` DataFrame to calculate the cumulative returns of the ETF portfolio.

5. Using hvPlot, create an interactive line plot that visualizes the cumulative return values of the ETF portfolio. Reflect the “time” column of the DataFrame on the x-axis. Make sure that you professionally style and format your visualization to enhance its readability.

#### Deploy the Notebook as a Web Application

For this part of the assignment, complete the following steps:

1. Use the Voilà library to deploy your notebook as a web application. You can deploy the web application locally on your computer.

2. Take a screen recording or screenshots to show how the web application appears when using Voilà. Include the recording or screenshots in the `README.md` file for your GitHub repository.

## Review the following code which imports the required libraries, initiates your SQLite database, popluates the database with records from the `etf.db` seed file that was included in your Starter_Code folder, creates the database engine, and confirms that data tables that it now contains.

In [2]:
# Importing the required libraries and dependencies
import numpy as np
import pandas as pd
import hvplot.pandas
import sqlalchemy

# Create a temporary SQLite database and populate the database with content from the etf.db seed file
database_connection_string = 'sqlite:///etf.db'

# Create an engine to interact with the SQLite database
engine = sqlalchemy.create_engine(database_connection_string)

# Confirm that table names contained in the SQLite database.
engine.table_names()

C:\Users\nehaja\Anaconda3\envs\dev\lib\site-packages\ipykernel_launcher.py:14: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)

['GDOT', 'GS', 'PYPL', 'SQ']

## Analyze a single asset in the FinTech ETF

For this part of the assignment, you’ll use SQL queries with Python, Pandas, and hvPlot to analyze the performance of a single asset from the ETF.

Complete the following steps:

1. Write a SQL `SELECT` statement by using an f-string that reads all the PYPL data from the database. Using the SQL `SELECT` statement, execute a query that reads the PYPL data from the database into a Pandas DataFrame.

2. Use the `head` and `tail` functions to review the first five and the last five rows of the DataFrame. Make a note of the beginning and end dates that are available from this dataset. You’ll use this information to complete your analysis.

3. Using hvPlot, create an interactive visualization for the PYPL daily returns. Reflect the “time” column of the DataFrame on the x-axis. Make sure that you professionally style and format your visualization to enhance its readability.

4. Using hvPlot, create an interactive visualization for the PYPL cumulative returns. Reflect the “time” column of the DataFrame on the x-axis. Make sure that you professionally style and format your visualization to enhance its readability.

### Step 1: Write a SQL `SELECT` statement by using an f-string that reads all the PYPL data from the database. Using the SQL `SELECT` statement, execute a query that reads the PYPL data from the database into a Pandas DataFrame.

In [5]:
# Write a SQL query to SELECT all of the data from the PYPL table
query = """
SELECT *
FROM PYPL
"""

# Use the query to read the PYPL data into a Pandas DataFrame
pypl_df = pd.read_sql_query(query, con=engine)

### Step 2: Use the `head` and `tail` functions to review the first five and the last five rows of the DataFrame. Make a note of the beginning and end dates that are available from this dataset. You’ll use this information to complete your analysis.

In [6]:
# View the first 5 rows of the DataFrame.
pypl_df.head()

,time,open,high,low,close,volume,daily_returns
0,2016-12-16 00:00:00.000000,39.90,39.90,39.12,39.32,7298861,-0.005564
1,2016-12-19 00:00:00.000000,39.40,39.80,39.11,39.45,3436478,0.003306
2,2016-12-20 00:00:00.000000,39.61,39.74,39.26,39.74,2940991,0.007351
3,2016-12-21 00:00:00.000000,39.84,40.74,39.82,40.09,5826704,0.008807
4,2016-12-22 00:00:00.000000,40.04,40.09,39.54,39.68,4338385,-0.010227

In [7]:
# View the last 5 rows of the DataFrame.
pypl_df.tail()

,time,open,high,low,close,volume,daily_returns
994,2020-11-30 00:00:00.000000,212.51,215.83,207.0900,214.200,8992681,0.013629
995,2020-12-01 00:00:00.000000,217.15,220.57,214.3401,216.520,9148174,0.010831
996,2020-12-02 00:00:00.000000,215.60,215.75,210.5000,212.660,6414746,-0.017827
997,2020-12-03 00:00:00.000000,213.33,216.93,213.1100,214.680,6463339,0.009499
998,2020-12-04 00:00:00.000000,214.88,217.28,213.0100,217.235,2118319,0.011901

### Step 3: Using hvPlot, create an interactive visualization for the PYPL daily returns. Reflect the “time” column of the DataFrame on the x-axis. Make sure that you professionally style and format your visualization to enhance its readability.

In [8]:
# Create an interactive visualization with hvplot to plot the daily returns for PYPL.
pypl_df['daily_returns'].hvplot(
    title = "Daily Returns for Paypal",
    x = "time",
    xlabel = "Time (specified in days)",
    ylabel = "Daily Returns",
)

:Curve   [time]   (daily_returns)

### Step 4: Using hvPlot, create an interactive visualization for the PYPL cumulative returns. Reflect the “time” column of the DataFrame on the x-axis. Make sure that you professionally style and format your visualization to enhance its readability.

In [9]:
# Create an interactive visaulization with hvplot to plot the cumulative returns for PYPL.
pypl_df['daily_returns'].cumsum().hvplot(
    title = "Cumulative Returns for Paypal",
    x = "time",
    xlabel = "Time (specified in days)",
    ylabel = "Cumulative Returns"
)

:Curve   [time]   (daily_returns)

## Optimize the SQL Queries

For this part of the assignment, you’ll continue to analyze a single asset (PYPL) from the ETF. You’ll use advanced SQL queries to optimize the efficiency of accessing data from the database.

Complete the following steps:

1. Access the closing prices for PYPL that are greater than 200 by completing the following steps:

1. Access the closing prices for PYPL that are greater than 200 by completing the following steps:

    - Write a SQL `SELECT` statement to select the dates where the PYPL closing price was higher than 200.0.

    - Select the “time” and “close” columns for those dates where the closing price was higher than 200.0.

    - Using the SQL statement, read the data from the database into a Pandas DataFrame, and then review the resulting DataFrame.

2. Find the top 10 daily returns for PYPL by completing the following steps:

    -  Write a SQL statement to find the top 10 PYPL daily returns. Make sure to do the following:

        * Use `SELECT` to select only the “time” and “daily_returns” columns.

        * Use `ORDER` to sort the results in descending order by the “daily_returns” column.

        * Use `LIMIT` to limit the results to the top 10 daily return values.

    - Using the SQL statement, read the data from the database into a Pandas DataFrame, and then review the resulting DataFrame.

### Step 1: Access the closing prices for PYPL that are greater than 200 by completing the following steps:

    - Write a SQL `SELECT` statement to select the dates where the PYPL closing price was higher than 200.0.

    - Select the “time” and “close” columns for those dates where the closing price was higher than 200.0.

    - Using the SQL statement, read the data from the database into a Pandas DataFrame, and then review the resulting DataFrame.

In [11]:
# Write a SQL SELECT statement to select the time and close columns 
# where the PYPL closing price was higher than 200.0.
query =  """
SELECT time, close
FROM PYPL
WHERE close > 200
"""
# Using the query, read the data from the database into a Pandas DataFrame
pypl_higher_than_200 = pd.read_sql_query(query, con=engine)

# Review the resulting DataFrame
pypl_higher_than_200

                          time    close
0   2020-08-05 00:00:00.000000  202.920
1   2020-08-06 00:00:00.000000  204.090
2   2020-08-25 00:00:00.000000  201.710
3   2020-08-26 00:00:00.000000  203.530
4   2020-08-27 00:00:00.000000  204.340
5   2020-08-28 00:00:00.000000  204.480
6   2020-08-31 00:00:00.000000  203.950
7   2020-09-01 00:00:00.000000  208.920
8   2020-09-02 00:00:00.000000  210.820
9   2020-09-03 00:00:00.000000  205.070
10  2020-10-12 00:00:00.000000  201.500
11  2020-10-13 00:00:00.000000  207.730
12  2020-10-14 00:00:00.000000  203.660
13  2020-10-15 00:00:00.000000  203.170
14  2020-10-16 00:00:00.000000  204.540
15  2020-10-19 00:00:00.000000  200.050
16  2020-10-20 00:00:00.000000  201.960
17  2020-10-21 00:00:00.000000  213.060
18  2020-10-22 00:00:00.000000  203.880
19  2020-10-23 00:00:00.000000  203.040
20  2020-10-27 00:00:00.000000  200.440
21  2020-11-05 00:00:00.000000  204.590
22  2020-11-06 00:00:00.000000  202.720
23  2020-11-23 00:00:00.000000  200.820
24  2020-11-24 00:00:00.000000  206.000
25  2020-11-25 00:00:00.000000  214.380
26  2020-11-27 00:00:00.000000  211.320
27  2020-11-30 00:00:00.000000  214.200
28  2020-12-01 00:00:00.000000  216.520
29  2020-12-02 00:00:00.000000  212.660
30  2020-12-03 00:00:00.000000  214.680
31  2020-12-04 00:00:00.000000  217.235

### Step 2: Find the top 10 daily returns for PYPL by completing the following steps:

    -  Write a SQL statement to find the top 10 PYPL daily returns. Make sure to do the following:

        * Use `SELECT` to select only the “time” and “daily_returns” columns.

        * Use `ORDER` to sort the results in descending order by the “daily_returns” column.

        * Use `LIMIT` to limit the results to the top 10 daily return values.

    - Using the SQL statement, read the data from the database into a Pandas DataFrame, and then review the resulting DataFrame.

In [12]:
# Write a SQL SELECT statement to select the time and daily_returns columns
# Sort the results in descending order and return only the top 10 return values
query =  """
SELECT time, daily_returns
FROM PYPL
ORDER BY daily_returns DESC
LIMIT 10
"""

# Using the query, read the data from the database into a Pandas DataFrame
pypl_top_10_returns = pd.read_sql_query(query, con=engine)

# Review the resulting DataFrame
pypl_top_10_returns

                         time  daily_returns
0  2020-03-24 00:00:00.000000       0.140981
1  2020-05-07 00:00:00.000000       0.140318
2  2020-03-13 00:00:00.000000       0.138700
3  2020-04-06 00:00:00.000000       0.100877
4  2018-10-19 00:00:00.000000       0.093371
5  2019-10-24 00:00:00.000000       0.085912
6  2020-11-04 00:00:00.000000       0.080986
7  2020-03-10 00:00:00.000000       0.080863
8  2020-04-22 00:00:00.000000       0.075321
9  2018-12-26 00:00:00.000000       0.074656

## Analyze the Fintech ETF Portfolio

For this part of the assignment, you’ll build the entire ETF portfolio and then evaluate its performance. To do so, you’ll build the ETF portfolio by using SQL joins to combine all the data for each asset.

Complete the following steps:

1. Write a SQL query to join each table in the portfolio into a single DataFrame. To do so, complete the following steps:

    - Use a SQL inner join to join each table on the “time” column. Access the “time” column in the `GDOT` table via the `GDOT.time` syntax. Access the “time” columns from the other tables via similar syntax.

    - Using the SQL query, read the data from the database into a Pandas DataFrame. Review the resulting DataFrame.

2. Create a DataFrame that averages the “daily_returns” columns for all four assets. Review the resulting DataFrame.

    > **Hint** Assuming that this ETF contains equally weighted returns, you can average the returns for each asset to get the average returns of the portfolio. You can then use the average returns of the portfolio to calculate the annualized returns and the cumulative returns. For the calculation to get the average daily returns for the portfolio, use the following code:
    >
    > ```python
    > etf_portfolio_returns = etf_portfolio['daily_returns'].mean(axis=1)
    > ```
    >
    > You can use the average daily returns of the portfolio the same way that you used the daily returns of a single asset.

3. Use the average daily returns in the `etf_portfolio_returns` DataFrame to calculate the annualized returns for the portfolio. Display the annualized return value of the ETF portfolio.

> **Hint**  To calculate the annualized returns, multiply the mean of the `etf_portfolio_returns` values by 252.
>
> To convert the decimal values to percentages, multiply the results by 100.

4. Use the average daily returns in the `etf_portfolio_returns` DataFrame to calculate the cumulative returns of the ETF portfolio.

5. Using hvPlot, create an interactive line plot that visualizes the cumulative return values of the ETF portfolio. Reflect the “time” column of the DataFrame on the x-axis. Make sure that you professionally style and format your visualization to enhance its readability.

### Step 1: Write a SQL query to join each table in the portfolio into a single DataFrame. To do so, complete the following steps:

    - Use a SQL inner join to join each table on the “time” column. Access the “time” column in the `GDOT` table via the `GDOT.time` syntax. Access the “time” columns from the other tables via similar syntax.

    - Using the SQL query, read the data from the database into a Pandas DataFrame. Review the resulting DataFrame.

In [13]:
# Wreate a SQL query to join each table in the portfolio into a single DataFrame 
# Use the time column from each table as the basis for the join
query = """
SELECT *
FROM GDOT
JOIN GS ON GDOT.time = GS.time
JOIN PYPL ON GDOT.time = PYPL.time
JOIN SQ ON GDOT.time = SQ.time;
"""
# Using the query, read the data from the database into a Pandas DataFrame
etf_portfolio = pd.read_sql_query(query, con=engine)

# Review the resulting DataFrame
etf_portfolio

,time,open,high,low,close,volume,daily_returns,time,open,high,...,close,volume,daily_returns,time,open,high,low,close,volume,daily_returns
0,2016-12-16 00:00:00.000000,24.41,24.7300,23.9400,23.9800,483544,-0.023218,2016-12-16 00:00:00.000000,242.80,243.1900,...,39.3200,7298861,-0.005564,2016-12-16 00:00:00.000000,14.290,14.4700,14.2300,14.3750,4516341,0.017339
1,2016-12-19 00:00:00.000000,24.00,24.0100,23.5500,23.7900,288149,-0.007923,2016-12-19 00:00:00.000000,238.34,239.7400,...,39.4500,3436478,0.003306,2016-12-19 00:00:00.000000,14.340,14.6000,14.3000,14.3600,3944657,-0.001043
2,2016-12-20 00:00:00.000000,23.75,23.9400,23.5800,23.8200,220341,0.001261,2016-12-20 00:00:00.000000,240.52,243.6500,...,39.7400,2940991,0.007351,2016-12-20 00:00:00.000000,14.730,14.8200,14.4100,14.4900,5207412,0.009053
3,2016-12-21 00:00:00.000000,23.90,23.9700,23.6900,23.8600,249189,0.001679,2016-12-21 00:00:00.000000,242.24,242.4000,...,40.0900,5826704,0.008807,2016-12-21 00:00:00.000000,14.450,14.5400,14.2701,14.3800,3901738,-0.007591
4,2016-12-22 00:00:00.000000,23.90,24.0100,23.7000,24.0050,383139,0.006077,2016-12-22 00:00:00.000000,241.23,242.8600,...,39.6800,4338385,-0.010227,2016-12-22 00:00:00.000000,14.330,14.3400,13.9301,14.0400,3874004,-0.023644
5,2016-12-23 00:00:00.000000,23.99,24.0000,23.7900,23.8100,113534,-0.008123,2016-12-23 00:00:00.000000,239.54,241.9000,...,39.5800,2525504,-0.002520,2016-12-23 00:00:00.000000,13.940,14.2400,13.8800,14.0800,1440289,0.002849
6,2016-12-27 00:00:00.000000,23.84,23.9800,23.6300,23.7550,54273,-0.002310,2016-12-27 00:00:00.000000,241.95,242.5899,...,39.7200,2209080,0.003537,2016-12-27 00:00:00.000000,14.120,14.2463,14.0000,14.0050,2169127,-0.005327
7,2016-12-28 00:00:00.000000,23.73,23.9400,23.6000,23.6700,98105,-0.003578,2016-12-28 00:00:00.000000,243.71,244.5000,...,39.5800,2721046,-0.003525,2016-12-28 00:00:00.000000,14.080,14.1200,13.8500,13.9550,1882397,-0.003570
8,2016-12-29 00:00:00.000000,23.65,23.9300,23.4500,23.5800,79427,-0.003802,2016-12-29 00:00:00.000000,240.75,241.0700,...,39.9700,3118262,0.009853,2016-12-29 00:00:00.000000,13.940,14.1100,13.6400,13.7250,2774798,-0.016482
9,2016-12-30 00:00:00.000000,23.53,23.5700,23.3900,23.5400,154961,-0.001696,2016-12-30 00:00:00.000000,239.28,240.5000,...,39.4700,3622222,-0.012509,2016-12-30 00:00:00.000000,13.710,13.7700,13.5300,13.6400,2758838,-0.006193
10,2017-01-03 00:00:00.000000,23.73,23.8100,23.3950,23.6100,201736,0.002974,2017-01-03 00:00:00.000000,242.70,244.9700,...,40.2500,6620546,0.019762,2017-01-03 00:00:00.000000,13.820,14.0150,13.6600,13.8100,3110610,0.012463
11,2017-01-04 00:00:00.000000,23.66,24.1700,23.5600,24.1189,238505,0.021554,2017-01-04 00:00:00.000000,241.44,243.3200,...,41.0000,5790753,0.018634,2017-01-04 00:00:00.000000,13.860,14.2600,13.7250,14.2500,4735274,0.031861
12,2017-01-05 00:00:00.000000,23.75,24.9900,23.6600,24.7600,397286,0.026581,2017-01-05 00:00:00.000000,242.63,243.2324,...,41.0600,5024495,0.001463,2017-01-05 00:00:00.000000,14.250,14.6100,14.0100,14.5500,4861651,0.021053
13,2017-01-06 00:00:00.000000,24.88,25.1100,24.7900,25.0500,232846,0.011712,2017-01-06 00:00:00.000000,242.29,246.2000,...,41.4400,4561434,0.009255,2017-01-06 00:00:00.000000,14.560,15.0747,14.5300,15.0100,6066772,0.031615
14,2017-01-09 00:00:00.000000,25.09,25.1000,24.6600,24.6900,341703,-0.014371,2017-01-09 00:00:00.000000,243.25,244.6900,...,41.3900,3079673,-0.001207,2017-01-09 00:00:00.000000,14.980,15.1950,14.8500,15.0500,4504808,0.002665
15,2017-01-10 00:00:00.000000,24.53,25.0500,24.4500,24.9800,226321,0.011746,2017-01-10 00:00:00.000000,240.87,243.4400,...,41.0900,3139301,-0.007248,2017-01-10 00:00:00.000000,15.090,15.4900,14.7000,14.9100,6416254,-0.009302
16,2017-01-11 00:00:00.000000,24.94,25.0400,24.6250,24.8700,185266,-0.004404,2017-01-11 00:00:00.000000,242.77,245.8400,...,41.2700,3589964,0.004381,2017-01-11 00:00:00.000000,14.950,14.9900,14.7100,14.9000,3385288,-0.000671
17,2017-01-12 00:00:00.000000,25.63,25.6300,24.5911,25.0000,211958,0.005227,2017-01-12 00:00:00.000000,245.06,245.4669,...,41.5600,3171153,0.007027,2017-01-12 00:00:00.000000,14.840,14.8800,14.5450,14.7400,2151793,-0.010738
18,2017-01-13 00:00:00.000000,25.00,25.3200,24.9900,25.2900,253619,0.011600,2017-01-13 00:00:00.000000,245.43,247.7700,...,41.6000,3142329,0.000962,2017-01-13 00:00:00.000000,14.790,14.9200,14.6900,14.7550,1795707,0.001018
19,2017-01-17 00:00:00.000000,25.79,25.7900,25.0800,25.2250,294879,-0.002570,2017-01-17 00:00:00.000000,242.94,243.0600,...,41.2700,4192211,-0.007933,2017-01-17 00:00:00.000000,14.690,14.7700,14.5400,14.6800,2467822,-0.005083
20,2017-01-18 00:00:00.000000,25.41,25.4900,25.1900,25.4500,181028,0.008920,2017-01-18 00:00:00.000000,236.00,237.6900,...,41.3400,3927767,0.001696,2017-01-18 00:00:00.000000,14.800,14.8400,14.6200,14.6200,3068951,-0.004087
21,2017-01-19 00:00:00.000000,25.72,25.8200,25.2600,25.2800,243953,-0.006680,2017-01-19 00:00:00.000000,234.07,234.7500,...,41.2700,4134165,-0.001693,2017-01-19 00:00:00.000000,14.640,14.8900,14.6000,14.7200,2255874,0.006840
22,2017-01-20 00:00:00.000000,25.29,25.6500,25.1500,25.5900,151424,0.012263,2017-01-20 00:00:00.000000,231.62,233.2300,...,41.6900,5934529,0.010177,2017-01-20 00:00:00.000000,14.750,15.0000,14.7150,14.8850,2905144,0.011209
23,2017-01-23 00:00:00.000000,25.48,25.6400,25.3500,25.6200,241898,0.001172,2017-01-23 00:00:00.000000,231.86,233.7520,...,41.6300,7236939,-0.001439,2017-01-23 00:00:00.000000,14.900,14.9600,14.5700,14.6001,3709132,-0.019140
24,2017-01-24 00:00:00.000000,25.66,26.1200,25.5900,26.1100,391861,0.019126,2017-01-24 00:00:00.000000,231.86,236.0600,...,41.9600,5218879,0.007927,2017-01-24 00:00:00.000000,14.610,14.7500,14.4300,14.6600,3524694,0.004103
25,2017-01-25 00:00:00.000000,26.25,26.6500,26.1100,26.6000,695711,0.018767,2017-01-25 00:00:00.000000,235.69,237.3300,...,41.7100,7510288,-0.005958,2017-01-25 00:00:00.000000,14.690,14.9900,14.5200,14.6050,3074682,-0.003752
26,2017-01-26 00:00:00.000000,26.58,28.9900,26.1300,26.6900,727158,0.003383,2017-01-26 00:00:00.000000,237.47,240.7900,...,41.5000,9488929,-0.005035,2017-01-26 00:00:00.000000,14.500,14.6300,14.1300,14.4100,4098861,-0.013352
27,2017-01-27 00:00:00.000000,26.80,26.8200,26.5000,26.6300,539724,-0.002248,2017-01-27 00:00:00.000000,236.90,237.9700,...,40.2700,20780970,-0.029639,2017-01-27 00:00:00.000000,14.470,14.5500,14.2650,14.5400,2050366,0.009022
28,2017-01-30 00:00:00.000000,26.60,26.8400,26.4000,26.8200,280392,0.007135,2017-01-30 00:00:00.000000,235.58,236.2900,...,39.8500,10176728,-0.010430,2017-01-30 00:00:00.000000,14.460,14.4900,14.1800,14.4550,2156141,-0.005846
29,2017-01-31 00:00:00.000000,26.75,26.9200,26.4900,26.7900,314761,-0.001119,2017-01-31 00:00:00.000000,232.85,234.3500,...,39.7800,7758619,-0.001757,2017-01-31 00:00:00.000000,14.400,14.7700,14.3650,14.6250,2960528,0.011761
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
969,2020-10-23 00:00:00.000000,58.84,59.8200,57.8800,59.7600,391831,0.018578,2020-10-23 00:00:00.000000,206.76,208.2100,...,203.0400,5836734,-0.004120,2020-10-23 00:00:00.000000,177.500,177.7900,173.3400,176.7700,7717064,0.004775
970,2020-10-26 00:00:00.000000,59.88,59.8800,56.6500,57.7500,287591,-0.033635,2020-10-26 00:00:00.000000,202.49,202.8100,...,197.2100,6117053,-0.028714,2020-10-26 00:00:00.000000,175.010,176.8600,166.7700,169.8900,12183441,-0.038921
971,2020-10-27 00:00:00.000000,58.07,58.3000,57.0700,57.3300,264413,-0.007273,2020-10-27 00:00:00.000000,200.00,200.5900,...,200.4400,3462757,0.016378,2020-10-27 00:00:00.000000,175.310,176.2600,169.2600,171.0100,12341315,0.006593
972,2020-10-28 00:00:00.000000,55.78,56.0047,54.7600,55.4900,491421,-0.032095,2020-10-28 00:00:00.000000,191.09,193.3650,...,192.3100,6684834,-0.040561,2020-10-28 00:00:00.000000,166.590,168.9399,164.4500,167.1300,9286880,-0.022689
973,2020-10-29 00:00:00.000000,55.51,56.5600,54.7200,56.0900,334462,0.010813,2020-10-29 00:00:00.000000,189.80,192.3500,...,195.0500,6246059,0.014248,2020-10-29 00:00:00.000000,170.080,172.0800,168.1100,169.8600,8148296,0.016335
974,2020-10-30 00:00:00.000000,55.66,55.7725,51.8250,53.3300,1151784,-0.049207,2020-10-30 00:00:00.000000,189.51,190.4000,...,186.3500,10318260,-0.044604,2020-10-30 00:00:00.000000,166.490,167.3974,152.4300,154.8700,28527409,-0.088249
975,2020-11-02 00:00:00.000000,53.87,55.4500,52.5350,52.7800,814851,-0.010313,2020-11-02 00:00:00.000000,192.00,192.7000,...,187.8800,9625499,0.008210,2020-11-02 00:00:00.000000,158.000,161.2400,152.1000,155.2300,15585600,0.002325
976,2020-11-03 00:00:00.000000,53.87,57.8000,52.8700,55.8400,1896848,0.057977,2020-11-03 00:00:00.000000,193.94,199.0000,...,179.6600,29090449,-0.043751,2020-11-03 00:00:00.000000,153.220,161.0500,151.1000,158.2200,14134458,0.019262
977,2020-11-04 00:00:00.000000,55.18,56.6099,52.9100,55.2600,1273232,-0.010387,2020-11-04 00:00:00.000000,196.25,200.8200,...,194.2100,14621064,0.080986,2020-11-04 00:00:00.000000,166.380,171.3600,162.1500,171.2900,13913429,0.082606
978,2020-11-05 00:00:00.000000,56.67,58.4350,53.0700,54.1000,983967,-0.020992,2020-11-05 00:00:00.000000,199.65,204.1200,...,204.5900,12618928,0.053447,2020-11-05 00:00:00.000000,177.100,177.2900,172.6500,175.5600,25861503,0.024928
979,2020-11-06 00:00:00.000000,54.53,56.2000,54.4300,55.5300,824192,0.026433,2020-11-06 00:00:00.000000,204.34,204.3900,...,202.7200,7075679,-0.009140,2020-11-06 00:00:00.000000,185.240,201.3300,182.9900,198.0993,51912386,0.128385
980,2020-11-09 00:00:00.000000,59.64,59.6400,54.2100,54.3900,959367,-0.020529,2020-11-09 00:00:00.000000,214.49,218.0000,...,184.7200,16430889,-0.088792,2020-11-09 00:00:00.000000,191.305,197.0000,181.8300,184.0000,26960258,-0.071173
981,2020-11-10 00:00:00.000000,54.73,55.6900,53.6600,54.6500,625102,0.004780,2020-11-10 00:00:00.000000,215.25,218.3800,...,183.3100,11599718,-0.007633,2020-11-10 00:00:00.000000,182.370,183.4600,167.1100,172.0900,27287979,-0.064728
982,2020-11-11 00:00:00.000000,55.01,55.9300,54.1000,55.7700,584340,0.020494,2020-11-11 00:00:00.000000,218.64,219.9200,...,192.3400,7959087,0.049261,2020-11-11 00:00:00.000000,179.650,183.9000,177.7000,183.3800,17121477,0.065605
983,2020-11-12 00:00:00.000000,55.34,56.4500,54.8000,55.3700,538700,-0.007172,2020-11-12 00:00:00.000000,215.22,216.8600,...,189.0900,5716107,-0.016897,2020-11-12 00:00:00.000000,184.260,185.1899,177.0000,178.5000,15722145,-0.026611
984,2020-11-13 00:00:00.000000,55.46,55.7550,54.1300,54.2950,346755,-0.019415,2020-11-13 00:00:00.000000,215.85,220.9600,...,188.7358,4003454,-0.001873,2020-11-13 00:00:00.000000,180.600,180.9000,175.5000,177.1600,11686412,-0.007507
985,2020-11-16 00:00:00.000000,54.34,55.4200,53.1900,53.8300,385200,-0.008564,2020-11-16 00:00:00.000000,223.53,224.6000,...,191.9600,9178675,0.017083,2020-11-16 00:00:00.000000,175.830,179.1600,173.0100,179.0900,13862918,0.010894
986,2020-11-17 00:00:00.000000,53.46,53.6600,52.1800,52.8200,659546,-0.018763,2020-11-17 00:00:00.000000,220.02,224.8500,...,192.3000,5380428,0.001771,2020-11-17 00:00:00.000000,180.120,190.7400,180.1200,187.8400,20695263,0.048858
987,2020-11-18 00:00:00.000000,52.92,53.8100,52.1900,52.2200,425334,-0.011359,2020-11-18 00:00:00.000000,225.00,227.7200,...,190.1200,6961251,-0.011336,2020-11-18 00:00:00.000000,187.490,187.5000,182.2703,185.5300,10410149,-0.012298
988,2020-11-19 00:00:00.000000,52.20,54.7350,51.4500,54.4800,805757,0.043278,2020-11-19 00:00:00.000000,224.30,224.9400,...,190.8800,8652714,0.003997,2020-11-19 00:00:00.000000,190.780,194.0100,185.7400,191.5800,23051083,0.032609
989,2020-11-20 00:00:00.000000,54.24,57.9300,54.0400,56.8700,1393010,0.043869,2020-11-20 00:00:00.000000,223.00,224.8100,...,192.6200,10621737,0.009116,2020-11-20 00:00:00.000000,193.690,200.9900,191.5500,195.9700,21110373,0.022915
990,2020-11-23 00:00:00.000000,57.39,58.3850,56.0200,57.3300,1201603,0.008089,2020-11-23 00:00:00.000000,226.06,230.0000,...,200.8200,10519696,0.042571,2020-11-23 00:00:00.000000,200.110,209.3600,199.2700,207.6900,23520379,0.059805
991,2020-11-24 00:00:00.000000,58.00,58.0900,55.5200,55.6700,1133712,-0.028955,2020-11-24 00:00:00.000000,231.10,238.1160,...,206.0000,13072036,0.025794,2020-11-24 00:00:00.000000,208.000,208.0400,199.5500,202.9550,22466075,-0.022798
992,2020-11-25 00:00:00.000000,55.93,57.4400,55.7500,56.9600,504254,0.023172,2020-11-25 00:00:00.000000,235.00,237.4500,...,214.3800,11779276,0.040680,2020-11-25 00:00:00.000000,207.450,214.5200,204.5700,212.9300,24394143,0.049149
993,2020-11-27 00:00:00.000000,57.24,57.7800,55.5500,56.0000,281544,-0.016854,2020-11-27 00:00:00.000000,237.00,237.3000,...,211.3200,4806373,-0.014274,2020-11-27 00:00:00.000000,215.000,215.0000,205.9000,212.5000,12798290,-0.002019
994,2020-11-30 00:00:00.000000,55.87,56.0899,53.1100,53.5500,361004,-0.043750,2020-11-30 00:00:00.000000,232.05,235.0000,...,214.2000,8992681,0.013629,2020-11-30 00:00:00.000000,213.000,213.5400,200.2300,210.9800,10485040,-0.007153
995,2020-12-01 00:00:00.000000,54.00,54.2500,52.0007,53.7900,546792,0.004482,2020-12-01 00:00:00.000000,231.96,234.8704,...,216.5200,9148174,0.010831,2020-12-01 00:00:00.000000,212.560,212.9500,200.5000,203.0000,9911165,-0.037823
996,2020-12-02 00:00:00.000000,53.20,53.7900,50.9400,52.3200,479868,-0.027328,2020-12-02 00:00:00.000000,232.08,238.1300,...,212.6600,6414746,-0.017827,2020-12-02 00:00:00.000000,200.130,204.0596,195.1300,202.1100,9968056,-0.004384
997,2020-12-03 00:00:00.000000,52.48,54.1600,52.0200,53.7600,474175,0.027523,2020-12-03 00:00:00.000000,237.29,238.8500,...,214.6800,6463339,0.009499,2020-12-03 00:00:00.000000,207.000,208.6900,204.0500,205.5300,6497836,0.016921
998,2020-12-04 00:00:00.000000,53.87,54.1900,53.0850,53.8600,83596,0.001860,2020-12-04 00:00:00.000000,237.70,239.6400,...,217.2350,2118319,0.011901,2020-12-04 00:00:00.000000,206.290,208.9500,203.5800,207.6164,2820542,0.010151

### Step 2: Create a DataFrame that averages the “daily_returns” columns for all four assets. Review the resulting DataFrame.

In [14]:
# Create a DataFrame that displays the mean value of the “daily_returns” columns for all four assets.
etf_portfolio_returns = etf_portfolio['daily_returns'].mean(axis=1)

# Review the resulting DataFrame
etf_portfolio_returns

0     -0.007038
1     -0.001216
2      0.008567
3     -0.001004
4     -0.008243
5     -0.001220
6      0.000304
7     -0.004176
8     -0.005080
9     -0.003673
10     0.010709
11     0.019658
12     0.010197
13     0.017107
14    -0.005331
15    -0.001469
16     0.003114
17    -0.001676
18     0.003887
19    -0.011994
20    -0.000325
21    -0.003625
22     0.009330
23    -0.004453
24     0.009025
25     0.005900
26    -0.001316
27    -0.008435
28    -0.005873
29    -0.002324
         ...
969    0.004273
970   -0.029937
971   -0.002944
972   -0.031380
973    0.010542
974   -0.046673
975    0.001536
976    0.018162
977    0.038580
978    0.020725
979    0.034325
980   -0.028081
981   -0.014000
982    0.034656
983   -0.016853
984   -0.001675
985    0.008388
986    0.010609
987   -0.009216
988    0.020272
989    0.017472
990    0.033899
991    0.003386
992    0.027063
993   -0.009501
994   -0.014635
995   -0.003990
996   -0.006288
997    0.011246
998    0.009108
Length: 999, dtype: float64

### Step 3: Use the average daily returns in the etf_portfolio_returns DataFrame to calculate the annualized returns for the portfolio. Display the annualized return value of the ETF portfolio.

In [15]:
# Use the average daily returns provided by the etf_portfolio_returns DataFrame 
# to calculate the annualized return for the portfolio. 
annualized_etf_portfolio_returns = (etf_portfolio_returns.mean() * 252) * 100

# Display the annualized return value of the ETF portfolio.
annualized_etf_portfolio_returns

43.827272400613595

### Step 4: Use the average daily returns in the `etf_portfolio_returns` DataFrame to calculate the cumulative returns of the ETF portfolio.

In [16]:
# Use the average daily returns provided by the etf_portfolio_returns DataFrame 
# to calculate the cumulative returns
etf_cumulative_returns = etf_portfolio_returns.cumsum()

# Display the final cumulative return value
etf_cumulative_returns

0     -0.007038
1     -0.008254
2      0.000313
3     -0.000691
4     -0.008934
5     -0.010154
6     -0.009850
7     -0.014026
8     -0.019106
9     -0.022779
10    -0.012070
11     0.007588
12     0.017785
13     0.034892
14     0.029561
15     0.028092
16     0.031206
17     0.029530
18     0.033418
19     0.021424
20     0.021099
21     0.017474
22     0.026805
23     0.022351
24     0.031376
25     0.037276
26     0.035960
27     0.027524
28     0.021651
29     0.019327
         ...
969    1.652641
970    1.622704
971    1.619760
972    1.588380
973    1.598922
974    1.552250
975    1.553786
976    1.571948
977    1.610527
978    1.631253
979    1.665578
980    1.637497
981    1.623497
982    1.658153
983    1.641301
984    1.639626
985    1.648013
986    1.658622
987    1.649406
988    1.669679
989    1.687151
990    1.721050
991    1.724436
992    1.751499
993    1.741998
994    1.727363
995    1.723372
996    1.717084
997    1.728330
998    1.737438
Length: 999, dtype: float64

### Step 5: Using hvPlot, create an interactive line plot that visualizes the cumulative return values of the ETF portfolio. Reflect the “time” column of the DataFrame on the x-axis. Make sure that you professionally style and format your visualization to enhance its readability.

In [17]:
# Using hvplot, create an interactive line plot that visualizes the ETF portfolios cumulative return values.
etf_cumulative_returns.hvplot.line(
    title = "ETF portfolios Cumulative Returns",
    x = "time",
    xlabel = "Time(specified in days)",
    ylabel = "Cumulative Returns",
    yformatter = '%.1f'
)

:Curve   [time]   (0)